### ISSUE TITLE
爬取了林志玲的微博评论 导出出现乱码

### ISSUE THREAD

**Issue by yao97** [zhouwei713/data_analysis#1]
![image](https://user-images.githubusercontent.com/20462086/64426934-7ecc1100-d0e2-11e9-86c9-50af7084921f.png)
![image](https://user-images.githubusercontent.com/20462086/64426953-8b506980-d0e2-11e9-8662-b27b02b5fe23.png)
![image](https://user-images.githubusercontent.com/20462086/64426985-9d320c80-d0e2-11e9-8266-db02403a080f.png)
是哪里出现问题了呢？

**Comment by zhouwei713** [comment]
就是编码的问题，你用 notepad ++ 打开试试，或者在保存文件的时候，把编码格式改成gbk试试

**Comment by yao97** [comment]
感谢回复，一开始没有注意到这个，直接打开utf-8的CSV文件会出现乱码，已经改正了，谢谢


在2019年9月6日 20:35，zhouluobo<notifications@github.com> 写道：

就是编码的问题，你用 notepad ++ 打开试试，或者在保存文件的时候，把编码格式改成gbk试试

**Comment by zhouwei713** [comment]
好的，不客气
